### ISSUE TITLE
动态加载JSON数据错误

### ISSUE THREAD

**Issue by tony2y** [dyw934854565/jsonview-vue#1]
您好 请问一下  ，我在使用该插件时， JSON 来源是从后台获取到的，格式和您的一模一样，但是还是会报错，所以是对动态的数据有特别要求吗？
![image](https://user-images.githubusercontent.com/38598582/56782629-7f8e9580-681a-11e9-9e57-a93a4945074a.png)
显示为这样的：
![image](https://user-images.githubusercontent.com/38598582/56782765-25420480-681b-11e9-814e-c80b68156925.png)

**Comment by dyw934854565** [comment]
你传入的json是一个jsonstring，不是一个对象。
请JSON.parse
看下面demo

https://code.h5jun.com/veman/edit?html,js,output

**Comment by tony2y** [comment]
好的  十分感谢
